// Felles design-tokens, logo og data
export const COL = {
  ink: "#0E1A2B",
  inkDeep: "#080F1B",
  inkSoft: "#2A3850",
  paper: "#F6F1E7",
  paperWarm: "#EFE7D6",
  paperDeep: "#E8DEC8",
  card: "#FBF7EC",
  border: "#D9CFB9",
  borderSoft: "#E6DCC4",
  gold: "#A8843E",
  goldSoft: "#C9A961",
  goldBright: "#D4AC4F",
  teal: "#0FA8A8",
  tealDeep: "#087F7F",
  sage: "#3F6B57",
  burgundy: "#8B2E3A",
  muted: "#6B6452",
};


export const PHASES = [
  { id: "akquisisjon", label: "Akquisisjon" },
  { id: "regulering", label: "Regulering" },
  { id: "prosjektering", label: "Prosjektering" },
  { id: "produksjon", label: "Produksjon" },
  { id: "overlevering", label: "Overlevering" },
];

export const PROJECTS = [
  {
    slug: "hamang",
    image: "/images/projects/hamang.jpg",
    website: "",
    name: "Hamang",
    location: "Sandvika",
    region: "Bærum",
    regionGroup: "Stor-Oslo",
    units: 700,
    kvm: 50000,
    statusShort: "Detaljregulering",
    statusCategory: "Regulering",
    partner: "Fastighets AB Balder",
    description:
      "Et nytt nabolag sentralt i Sandvika utviklet i partnerskap med Fastighets AB Balder. Detaljreguleringen forventes vedtatt i løpet av 2026, med byggestart for første trinn i 2027.",
    lat: 59.89,
    lng: 10.52,
    phaseProgress: 0.32,
    timeline: { start: 2024, end: 2034 },
  },
  {
    slug: "steinan",
    image: "/images/projects/steinan.jpg",
    website: "",
    name: "Steinan",
    location: "Trondheim",
    region: "Trondheim",
    regionGroup: "Trøndelag",
    units: 577,
    kvm: 32000,
    statusShort: "Under produksjon",
    statusCategory: "Produksjon",
    partner: "Fredensborg",
    description:
      "Transformasjon av tidligere Steinan studentby til et større boligområde sentralt i Trondheim, kjøpt sammen med Fredensborg fra Studentsamskipnaden. Trinn 1 er overlevert. Trinn 2 med 130 leiligheter er igangsatt med 70 % salgsgrad.",
    lat: 63.41,
    lng: 10.43,
    phaseProgress: 0.78,
    timeline: { start: 2020, end: 2030 },
  },
  {
    slug: "sjokanten",
    image: "/images/projects/sjokanten.jpg",
    website: "",
    name: "Sjøkanten",
    location: "Steinkjer",
    region: "Steinkjer",
    regionGroup: "Trøndelag",
    units: 300,
    kvm: 20000,
    statusShort: "Rammesøknad",
    statusCategory: "Prosjektering",
    partner: "Ligna · PLG",
    description:
      "Sjønære leiligheter i hjertet av Steinkjer. Forprosjekt for første salgstrinn er igangsatt på den byggeklare delen av tomten.",
    lat: 64.01,
    lng: 11.49,
    phaseProgress: 0.52,
    timeline: { start: 2022, end: 2032 },
  },
  {
    slug: "linaaskollen",
    image: "/images/projects/linaaskollen.jpg",
    website: "",
    name: "Linåskollen",
    location: "Ski",
    region: "Ski",
    regionGroup: "Stor-Oslo",
    units: 183,
    kvm: 16645,
    statusShort: "Under produksjon",
    statusCategory: "Produksjon",
    partner: "Backe Prosjekt",
    description:
      "Boliger i kort gangavstand fra Ski stasjon. Bygging er igangsatt med Veidekke som totalentreprenør, og nytt trinn med rekkehus planlegges senere i året.",
    lat: 59.72,
    lng: 10.84,
    phaseProgress: 0.72,
    timeline: { start: 2021, end: 2028 },
  },
  {
    slug: "solfast",
    image: "/images/projects/solfast.jpg",
    website: "",
    name: "Sølfast Park",
    location: "Drammen",
    region: "Drammen",
    regionGroup: "Buskerud",
    units: 156,
    kvm: 12500,
    statusShort: "Detaljregulering",
    statusCategory: "Regulering",
    partner: "Fastighets AB Balder",
    description:
      "Et nytt boligområde i Drammen utviklet i partnerskap med Fastighets AB Balder. Plan ferdigstilles i løpet av 2026.",
    lat: 59.74,
    lng: 10.20,
    phaseProgress: 0.28,
    timeline: { start: 2023, end: 2030 },
  },
  {
    slug: "sundsoya",
    image: "/images/projects/sundsoya.jpg",
    website: "",
    name: "Sundsøya",
    location: "Inderøy",
    region: "Inderøy",
    regionGroup: "Trøndelag",
    units: 70,
    kvm: 5000,
    statusShort: "Rammesøknad",
    statusCategory: "Prosjektering",
    partner: "PLG Holding",
    description:
      "Et nytt sjønært bomiljø ved Sundsøya i Inderøy med både leiligheter og eneboliger.",
    lat: 63.85,
    lng: 11.31,
    phaseProgress: 0.48,
    timeline: { start: 2023, end: 2028 },
  },
];

export const COMPLETED = [
  {
    name: "Steinan Park",
    location: "Trondheim",
    units: 146,
    year: 2023,
    partner: "Fredensborg",
    note: "Norges mest solgte boligprosjekt 2023",
  },
  {
    name: "Smedparken",
    image: "/images/projects/smedparken.jpg",
    location: "Trondheim",
    units: 109,
    year: 2023,
    partner: "Krofu",
    note: "Selveierleiligheter på Heimdal",
  },
  {
    name: "Linåstunet",
    image: "/images/projects/linastunet.jpg",
    location: "Ski",
    units: 70,
    year: 2024,
    partner: "Backe",
    note: "Rekkehus i sentrumsnær beliggenhet",
  },
  {
    name: "Aagards Plass",
    image: "/images/projects/aagardsplass.jpg",
    location: "Sandefjord",
    units: 84,
    year: 2023,
    partner: "Fastighets AB Balder",
    note: "Sentrumsutvikling med næring og bolig",
  },
  {
    name: "Dønskiveien",
    location: "Oslo",
    units: 32,
    year: 2022,
    partner: "Fastighets AB Balder",
    note: "Effektive leiligheter i etablert nabolag",
  },
];

export const NEWS = [
  {
    slug: "steinan-overlevering-2026",
    date: "2026-03-25",
    project: "Steinan, Trondheim",
    title: "126 leiligheter overlevert på Steinan",
    excerpt:
      "Trinn 1 av Steinan er nå overlevert til kjøperne. De siste leilighetene tas over påske, og trinn 2 med 130 nye leiligheter er allerede igangsatt med 70 % salgsgrad.",
    body: [
      "Trinn 1 av Steinan er nå overlevert til kjøperne. De siste leilighetene tas over påske, og trinn 2 med 130 nye leiligheter er allerede igangsatt.",
      "Trinn 2 har 70 % salgsgrad ved oppstart, og forventes ferdigstilt i 2027. Prosjektet utvikles i partnerskap med Fredensborg, og er kjøpt fra Studentsamskipnaden i Trondheim.",
    ],
  },
  {
    slug: "linaaskollen-byggestart-2026",
    date: "2026-02-12",
    project: "Linåskollen, Ski",
    title: "Byggestart for 50 leiligheter på Linåskollen",
    excerpt:
      "Bygging er igangsatt med Veidekke som totalentreprenør. 27 av 50 leiligheter er solgt, og nytt trinn med rekkehus planlegges senere i året.",
    body: [
      "Bygging er igangsatt med Veidekke som totalentreprenør. 27 av 50 leiligheter er solgt, og innflytting er forventet i 2027.",
      "Linåskollen ligger i kort gangavstand fra Ski stasjon, og prosjektet utvikles i partnerskap med Backe Prosjekt. Et nytt trinn med rekkehus er planlagt senere i året.",
    ],
  },
  {
    slug: "steinan-norges-mest-solgte-2023",
    date: "2024-01-20",
    project: "Steinan Park, Trondheim",
    title: "Norges mest solgte boligprosjekt 2023",
    excerpt:
      "Steinan Park ble fjorårets soleklare ener — med 146 salg ble det flest i Norge i 2023.",
    body: [
      "Steinan Park ble fjorårets soleklare ener i det norske boligmarkedet. Med 146 salg ble det det mest solgte boligprosjektet i Norge i 2023.",
      "Prosjektet ligger sentralt i Trondheim og utvikles i partnerskap med Fredensborg. Startskuddet for byggestarten har nylig gått.",
    ],
  },
];
